id: I4C4AC2D6
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1876
  ocr_info:
    timestamp: 03/21/23T14:18:14
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 23:20:17.128527+00:00
last_modified: 2024-02-28 23:20:17.128534+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1876
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1876
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྟོང་ཆེན་མོ་རབ་ཏུ་འཇོམས་པའི་མདོ།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.970874730496766
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN1878:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1878
      total_pages: 90
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1878.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.970874730496766
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
